// export const povWords = [
//   "First person",
//   "Second person",
//   "Third person limited",
//   "Third person omniscient",
//   "Objective viewpoint",
//   "Subjective viewpoint",
//   "Personal perspective",
//   "Cultural perspective",
//   "Historical perspective",
//   "Political perspective",
//   "Social perspective",
//   "Philosophical viewpoint",
//   "Moral perspective",
//   "Emotional viewpoint",
//   "Psychological viewpoint",
//   "Biased perspective",
//   "Objective analysis",
//   "Subjective interpretation",
//   "Critical lens",
//   "Worldview",
// ];

// export const comparisonWords = [
//   "Similarity",
//   "Difference",
//   "Akin",
//   "Dissimilar",
//   "Analogous",
//   "Discrepancy",
//   "Corresponding",
//   "Distinct",
//   "Comparable",
//   "Disparity",
//   "Resemblance",
//   "Dissemblance",
//   "Likeness",
//   "Contrast",
// ];

// export const interpretationWords = [
//   "analyzes",
//   "examines",
//   "interpret",
//   "Evaluate",
//   "Scrutinize",
//   "Break down",
//   "Decode",
//   "Unpack",
//   "Unravel",
//   "Dissect",
//   "Comprehend",
//   "Understand",
//   "Decipher",
//   "Untangle",
//   "Explore",
//   "Investigate",
//   "Uncover",
//   "Elucidate",
//   "Clarify",
//   "Explicate",
// ];

// export const interactWords = [
//   "conflicting",
//   "problematic",
//   "helpful",
//   "suportive",
//   "negative",
//   "positive",
//   "hostile",
//   "intense",
//   "collaborative",
//   "welcoming",
//   "cordial",
//   "neutral",
// ];

// export const themeWords = [
//   "Beauty",
//   "good versus evil",
//   "coming of age",
//   "loyalty",
//   "betrayal",
//   "life and death",
//   "justice",
//   "family",
//   "power",
//   "change versus tradition",
// ];
