export const themeStems = [
  "The theme of the text is_____",
  "The theme of this piece is_____",
  "The central idea of this piece is_____",
  "The theme of _____ is present throughout the text, as seen in_____",
  "One of the major themes of this text is_____",
  "Through [literary device], the author conveys the theme of_____",
  "The author employs [symbol/imagery/metaphor] to develop the theme of_____",
  "The theme of _____ is developed through the actions of [character's name], as seen in_____",
  "A recurring theme in this text is_____",
  "The theme of _____ is relevant in today's society because_____",
  "The author's use of [literary device] helps to reinforce the theme of_____",
  "The theme of _____ is explored in depth through the interactions between [character's name] and [character's name]_____",
  "The theme of _____ is significant because it reveals_____",
];

export const interactStems = [
  "The character(s) of the text are_____",
  "The idea(s) of the text are_____",
  "The event(s) of the text are_____",
  "The relationship between the main character and _____ shows_____",
  "The relationship between the idea and _____ shows_____",
  "The relationship between the event and _____ shows_____",
  "This characters highlights how_____",
  "These ideas highlight how_____",
  "This event highlights how_____",
  "This idea behind_____shows how the characters interact_____",
  " The idea of___affects the relationship between (character 1) and (character 2)since_____",
];

export const interpretationStems = [
  "The author's use of [specific word] in this passage connotes_____",
  "By choosing to use the phrase [phrase], the author is suggesting_____",
  "It's important to consider the technical meaning of [word] in this context because_____",
  "The figurative meaning of [phrase] used here is significant because_____",
  "The author's word choice in this paragraph creates a tone of_____",
  "This specific word can be interpreted as having a connotative meaning of_____",
  "In order to fully analyze the meaning of this text, we must consider the nuances of_____",
  "The author's decision to use [word] rather than [alternative word] contributes to the overall tone of the text by_____",
  "It's worth examining the multiple meanings of [phrase] in this passage because_____",
  "The way the author uses language in this paragraph reveals their attitude towards_____",
];

export const comparisonStems = [
  "In comparison to_____",
  "When considering both_____",
  "By contrast_____",
  "While there are similarities between_____",
  "Conversely_____",
  "In a similar vein_____",
  "On the other hand_____",
  "In contrast to_____",
  "Similarly_____",
  "By comparison_____",
  "Whereas_____",
  "Unlike_____",
  "At the same time_____",
  "While [subject A] has [attribute X], [subject B] has [attribute Y]_____",
  "[Subject A] and [subject B] share [attribute X], but differ in [attribute Y]_____",
];

export const povStems = [
  "From [character's name] point of view,_____",
  "Considering the perspective of [character's name],_____",
  "[Character's name] sees the situation as_____",
  "Looking through the eyes of [character's name],_____",
  "If we view this situation from [character's name] perspective, _____",
  "In [character's name] opinion,_____",
  "It's interesting to note how [character's name] views_____",
  "From where [character's name] stands, it appears that_____",
  "[Character's name] has a unique perspective on_____",
  "Seeing this from [character's name]'s point of view, we can understand_____",
];

export const evidenceStem = [
  "The text states, [Quote]",
  "According to the article, [Quote]",
  "In the article, the author states, [Quote]",
  "In the text, the author writes, [Quote]",
  "It was discovered that, [Quote]",
  "The narrator states that, [Quote]",
  "The character states, [Quote]",
  "[Expert's name] suggests that, [Quote]",
  "As [author's name] explains, [Quote]",
  "In support of this claim, [Quote]",
  "[Statistic/fact] indicates that _____",
  "[Witness's name] observed that, [Quote]",
  "[Quote from a reputable source],",
  "As demonstrated by [experiment/study],",
  "[Historical event] serves as evidence for_____",
  "[Personal experience] provides evidence that_____",
];

export const reasoningStem = [
  "This indicates_____",
  "This supports the claim_____",
  "This is important because_____",
  "This suggests that_____",
  "This shows_____",
  "This means_____",
  "This reveals_____",
  "This expresses the idea that_____",
  "This confirms_____",
  "The author's point is that_____",
  "This is significant because_____",
];

export const transitionWords = [
  "Additionally,_____",
  "Furthermore,_____",
  "Moreover,_____",
  "In addition,_____",
  "Besides,_____",
  "Likewise,_____",
  "Equally important,_____",
  "Similarly,_____",
  "Not only... but also,_____",
  "As well as,_____",
  "Let's not forget,_____",
  "Coupled with,_____",
  "What's more,_____",
  "Correspondedly,_____",
  "It is also essential to note,_____",
  "Another key point,_____",
  "In the same vein,_____",
  "Along the same lines,_____",
];

export const conclusionStem = [
  "In conclusion,_____",
  "To end,_____",
  "In conclusion, it is evident that_____",
  "Ultimately, the evidence supports the idea that_____",
  "After considering all the facts, it is clear that_____",
  "To sum up, the key takeaways from this essay are_____",
  "In summary, it can be concluded that_____",
  "In light of the evidence presented, it is safe to say that_____",
  "In the end, the arguments presented here demonstrate that_____",
  "As demonstrated by the evidence, it is clear that_____",
  "To conclude, this essay has shown that_____",
  "Overall, the findings of this study suggest that_____",
];
