export const themeStems = [
  "The theme of the text is_____. ",
  "The theme of this piece is_____.",
  "The central idea of this piece is_____.",
];

// export const themeWords = [
//   "Beauty",
//   "good versus evil",
//   "coming of age",
//   "loyalty",
//   "betrayal",
//   "life and death",
//   "justice",
//   "family",
//   "power",
//   "change versus tradition",
// ];

export const evidenceStem = [
  "The text states,",
  "According to the article,",
  "In the article, the author states,",
  "In the text, the author writes,",
  "It was discovered that,",
  "The narrator states that,",
  "The character states,",
];

export const reasoningStem = [
  "This indicates_____.",
  "This supports the claim_____.",
  "This is important because_____.",
  "This suggests that_____.",
  "This shows_____.",
  "This means_____.",
  "This reveals_____.",
  "This expresses the idea that_____.",
  "This confirms_____.",
  "The author's point is that_____.",
  "This is significant because_____.",
];
export const conclusionStem = [
  "In conclusion,_____.",
  "To end,_____.",
  "In conclusion, it is evident that_____.",
  "Ultimately, the evidence supports the idea that_____.",
  "After considering all the facts, it is clear that_____.",
  "To sum up, the key takeaways from this essay are_____.",
  "In summary, it can be concluded that_____.",
  "In light of the evidence presented, it is safe to say that_____.",
  "In the end, the arguments presented here demonstrate that_____.",
  "As demonstrated by the evidence, it is clear that_____.",
  "To conclude, this essay has shown that_____.",
  "Overall, the findings of this study suggest that_____.",
];

export const interactStems = [
  "The character(s) of the text are_____.",
  "The idea(s) of the text are_____.",
  "The event(s) of the text are_____.",
  "The relationship between the main character and _____ shows_____.",
  "The relationship between the idea and _____ shows_____.",
  "The relationship between the event and _____ shows_____.",
  "This characters highlights how_____.",
  "These ideas highlight how_____.",
  "This event highlights how_____.",
  "This idea behind_____shows how the characters interact_____.",
  " The idea of___affects the relationship between (character 1) and (character 2)since_____.",
];

// export const interactWords = [
//   "conflicting",
//   "problematic",
//   "helpful",
//   "suportive",
//   "negative",
//   "positive",
//   "hostile",
//   "intense",
//   "collaborative",
//   "welcoming",
//   "cordial",
//   "neutral",
// ];

export const interpretationStems = [
  "The author's use of [specific word] in this passage connotes_____.",
  "By choosing to use the phrase [phrase], the author is suggesting_____.",
  "It's important to consider the technical meaning of [word] in this context because_____.",
  "The figurative meaning of [phrase] used here is significant because_____.",
  "The author's word choice in this paragraph creates a tone of_____.",
  "This specific word can be interpreted as having a connotative meaning of_____.",
  "In order to fully analyze the meaning of this text, we must consider the nuances of_____.",
  "The author's decision to use [word] rather than [alternative word] contributes to the overall tone of the text by_____.",
  "It's worth examining the multiple meanings of [phrase] in this passage because_____.",
  "The way the author uses language in this paragraph reveals their attitude towards_____.",
];

// export const interpretationWords = [
//   "analyzes",
//   "examines",
//   "interpret",
//   "Evaluate",
//   "Scrutinize",
//   "Break down",
//   "Decode",
//   "Unpack",
//   "Unravel",
//   "Dissect",
//   "Comprehend",
//   "Understand",
//   "Decipher",
//   "Untangle",
//   "Explore",
//   "Investigate",
//   "Uncover",
//   "Elucidate",
//   "Clarify",
//   "Explicate",
// ];

export const comparisonStems = [
  "In comparison to_____.",
  "When considering both_____.",
  "By contrast_____.",
  "While there are similarities between_____.",
  "Conversely_____.",
  "In a similar vein_____.",
  "On the other hand_____.",
  "In contrast to_____.",
  "Similarly_____.",
  "By comparison_____.",
  "Whereas_____.",
  "Unlike_____.",
  "At the same time_____.",
  "While [subject A] has [attribute X], [subject B] has [attribute Y]_____.",
  "[Subject A] and [subject B] share [attribute X], but differ in [attribute Y]_____.",
];

// export const comparisonWords = [
//   "Similarity",
//   "Difference",
//   "Akin",
//   "Dissimilar",
//   "Analogous",
//   "Discrepancy",
//   "Corresponding",
//   "Distinct",
//   "Comparable",
//   "Disparity",
//   "Resemblance",
//   "Dissemblance",
//   "Likeness",
//   "Contrast",
// ];

export const povStems = [
  "From [character's name] point of view,_____.",
  "Considering the perspective of [character's name],_____.",
  "[Character's name] sees the situation as_____.",
  "Looking through the eyes of [character's name],_____.",
  "If we view this situation from [character's name] perspective, _____.",
  "In [character's name] opinion,_____.",
  "It's interesting to note how [character's name] views_____.",
  "From where [character's name] stands, it appears that_____.",
  "[Character's name] has a unique perspective on_____.",
  "Seeing this from [character's name]'s point of view, we can understand_____.",
];

// export const povWords = [
//   "First person",
//   "Second person",
//   "Third person limited",
//   "Third person omniscient",
//   "Objective viewpoint",
//   "Subjective viewpoint",
//   "Personal perspective",
//   "Cultural perspective",
//   "Historical perspective",
//   "Political perspective",
//   "Social perspective",
//   "Philosophical viewpoint",
//   "Moral perspective",
//   "Emotional viewpoint",
//   "Psychological viewpoint",
//   "Biased perspective",
//   "Objective analysis",
//   "Subjective interpretation",
//   "Critical lens",
//   "Worldview",
// ];
